### ISSUE TITLE
AGENDAMENTO

### ISSUE THREAD

**Issue by informaticavera** [novosga/scheduling-bundle#1]
donde puede conseguir la parte de agendamento??
https://demo.euagendei.online/#/

Este módulo es compatible con NOVOSGA 1.5????

**Comment by rogeriolino** [comment]
Somente para v2.0

**Comment by informaticavera** [comment]
Y puedes ponerte en contacto conmigo para trabajar juntos???
Podriamos hacer un proyecto para actualizar nuestra versión de 1.5 a 2, añadiendo la funcionalidad de login LDAP y el modulo de agendamento.

**Comment by rogeriolino** [comment]
Muchas gracias pero no me interesa.
